wordpress:
  image:  devregistry.dataman-inc.com:5000/library/wordpress
  restart: always
  ports:
    - "${default_port}:80"
  environment:
    WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
    WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
    WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
