mysql:
  image:  catalog.shurenyun.com/library/mysql
  restart: always
  ports:
    - "3306:3306"
  environment:
    MYSQL_ROOT_PASSWORD: foobar
wordpress:
  image:  catalog.shurenyun.com/library/wordpress
  restart: always
  ports:
    - "80:80"
  environment:
    WORDPRESS_DB_HOST: mysql:3306
    WORDPRESS_DB_USER: root
    WORDPRESS_DB_PASSWORD: foobar
  links:
    - mysql:mysql

